%% get curvature, torsion with Pressure
load Material_fit_6088.mat
lambda1 = Material_fit(:,2);

alpha = 85*pi/180;
beta = 58*pi/180;
Ro = 13/64*.0254;
L = 1;

 delta = L.*Ro.^(-1).*cos(alpha).^3.*cos(beta).^3.*csc(alpha+(-1).*beta) ...
  .^2.*csc(alpha+beta).*(((-1).*lambda1.^2+sec(beta).^2).*tan(alpha) ...
  .^2+sec(alpha).^4.*sec(beta).^4.*(cos(alpha).^6.*((-1)+ ...
  lambda1.^2.*cos(alpha).^2).*cos(beta).^6.*((-1)+lambda1.^2.*cos( ...
  beta).^2).*(tan(alpha)+(-1).*tan(beta)).^4).^(1/2)+(2.*lambda1.^2+ ...
  (-1).*sec(alpha).^2+(-1).*sec(beta).^2).*tan(alpha).*tan(beta)+(( ...
  -1).*lambda1.^2+sec(alpha).^2).*tan(beta).^2);

[Material_fit(:,1) (lambda1-1)./(2*Ro) delta]